public struct DefaultSaltingService : SaltingServiceProtocol {
    public var salt: String
    
    // This salt should actually be generated by this struct, this is for testing purposes
    public init(salt: String = "") {
        self.salt = salt
    }
    
}
